services:  
  db:
    image: arm64v8/mysql:8.4
    platform: linux/arm64
    restart: always
    container_name: g7s-task-db
    volumes:
        - mysql-data:/var/lib/mysql
        - ./runtime/logs:/var/log/mysql
    environment:
        MYSQL_RANDOM_ROOT_PASSWORD: yes
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
        - "33063:3306"